CREATE TABLE orders (
  id   BIGSERIAL PRIMARY KEY,
  user_id  INT NOT NULL REFERENCES users (id) UNIQUE,
  order_status OrderStatus NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


