CREATE TABLE users (
  id   BIGSERIAL PRIMARY KEY,
  email TEXT  UNIQUE  NOT NULL,
  hashed_password TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
