// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orderItem.sql

package db

import (
	"context"
)

const orderItem_ClearOrders = `-- name: OrderItem_ClearOrders :exec
DELETE FROM order_items
WHERE order_id = 1
`

func (q *Queries) OrderItem_ClearOrders(ctx context.Context) error {
	_, err := q.db.Exec(ctx, orderItem_ClearOrders)
	return err
}

const orderItem_DecrementQuantity = `-- name: OrderItem_DecrementQuantity :exec
UPDATE order_items
  SET quantity = $2
WHERE id = $1
`

type OrderItem_DecrementQuantityParams struct {
	ID       int64
	Quantity int32
}

func (q *Queries) OrderItem_DecrementQuantity(ctx context.Context, arg OrderItem_DecrementQuantityParams) error {
	_, err := q.db.Exec(ctx, orderItem_DecrementQuantity, arg.ID, arg.Quantity)
	return err
}

const orderItem_DeleteItem = `-- name: OrderItem_DeleteItem :exec
DELETE FROM order_items
WHERE order_id = $1 AND product_id = $2
`

type OrderItem_DeleteItemParams struct {
	OrderID   int32
	ProductID int32
}

func (q *Queries) OrderItem_DeleteItem(ctx context.Context, arg OrderItem_DeleteItemParams) error {
	_, err := q.db.Exec(ctx, orderItem_DeleteItem, arg.OrderID, arg.ProductID)
	return err
}

const orderItem_GetAll = `-- name: OrderItem_GetAll :many
SELECT id, order_id, product_id, quantity, added_at, created_at, updated_at FROM order_items
ORDER BY created_at DESC
`

func (q *Queries) OrderItem_GetAll(ctx context.Context) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, orderItem_GetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.AddedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderItem_GetAllOrderId = `-- name: OrderItem_GetAllOrderId :many
SELECT id, order_id, product_id, quantity, added_at, created_at, updated_at FROM order_items
WHERE order_id = $1
ORDER BY created_at DESC
`

func (q *Queries) OrderItem_GetAllOrderId(ctx context.Context, orderID int32) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, orderItem_GetAllOrderId, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.AddedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderItem_IncrementQuantity = `-- name: OrderItem_IncrementQuantity :exec
UPDATE order_items
  SET quantity = $2
WHERE id = $1
`

type OrderItem_IncrementQuantityParams struct {
	ID       int64
	Quantity int32
}

func (q *Queries) OrderItem_IncrementQuantity(ctx context.Context, arg OrderItem_IncrementQuantityParams) error {
	_, err := q.db.Exec(ctx, orderItem_IncrementQuantity, arg.ID, arg.Quantity)
	return err
}
