definitions:
  auth.LoginDto:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:1323
info:
  contact:
    email: instashop@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a simple e-commerce server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Instashop Swagger API
  version: "1.0"
paths:
  /auth/register:
    post:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Auth_Register
  /auth/send-otp:
    post:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Auth_SendEmailOtp
  /auth/verify-otp:
    post:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Auth_VerifyOtp
  /login:
    post:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/auth.LoginDto'
            type: array
      tags:
      - Auth_Login
  /orders/{id}:
    delete:
      parameters:
      - description: id of order
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Order_Delete
    get:
      parameters:
      - description: id of order
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Order_GetOne
    patch:
      parameters:
      - description: id of order
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Order_Update
    post:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Order_Create
  /product/{id}:
    delete:
      parameters:
      - description: id of product
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Product_Delete
    patch:
      description: Product update
      parameters:
      - description: id of product
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Product_Update
  /products:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Product_GetAll
    post:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Product_Create
  /products/{id}:
    get:
      parameters:
      - description: id of product
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Product_GetOne
swagger: "2.0"
