basePath: /v2
definitions:
  controllers.LoginDto:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: instashop@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a simple e-commerce server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Instashop Swagger API
  version: "1.0"
paths:
  /login:
    post:
      description: Login route
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.LoginDto'
            type: array
      summary: Login routes
      tags:
      - Login
  /product/{id}:
    patch:
      description: Product update
      parameters:
      - description: id of product
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - ProductUpdate
  /send-otp:
    post:
      description: Login routes
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Send otp route
      tags:
      - SendOtp
swagger: "2.0"
